name: 'Build and Push Docker Image'

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # Gera a tag da imagem. Ex: seu-usuario/seu-repo:latest e seu-usuario/seu-repo:<git-sha>
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ricasdev:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ricasdev:${{ github.sha }}
          push: true
