name: 'Label Pull Requests'

on:
  pull_request:
    types: [ opened ]
  issues:
    types: [ all ]

jobs:
  labeler:
    name: Apply Labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Run Labeler
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
