# .github/workflows/verify_merge_back.yml

# Nome do workflow que aparecerá na aba "Actions" do seu repositório
name: 'Verify Merge Back'

# Define os gatilhos (triggers) para este workflow
on:
  # 1. Executa em pushes diretos para a branch 'master'
  push:
    branches: [ master ]
  
  # 2. Executa em eventos de pull request para a branch 'master'
  pull_request:
    branches: [ master ]

# Agrupa todos os jobs que serão executados
jobs:
  # Define um único job chamado 'check-if-branch-is-updated'
  check-if-branch-is-updated:
    # Nome que será exibido na interface do GitHub
    name: Check if branch is up-to-date
    # O tipo de máquina virtual para executar o job
    runs-on: ubuntu-latest

    # A sequência de passos que o job executará
    steps:
      # 1. Clona o repositório
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # 'fetch-depth: 0' garante que todo o histórico de commits seja baixado.
          fetch-depth: 0

      # 2. Torna o script executável
      - name: Make script executable
        run: chmod +x .github/scripts/verify_merge_back.sh

      # 3. Executa o script de verificação
      # A variável de ambiente TARGET_BRANCH é necessária para o contexto de Pull Request.
      # Para um push direto na 'master', o script usará "master" como padrão,
      # comparando a branch com ela mesma, o que sempre resultará em sucesso.
      - name: Run verify merge back script
        run: .github/scripts/verify_merge_back.sh
        env:
          TARGET_BRANCH: ${{ github.base_ref || 'master' }}
